### ISSUE TITLE
Review structure and library API

### ISSUE THREAD

**Issue by rgbkrk** [rgbkrk/gorcs#1]
It would be cool if @smashwilson, @jamiehannaford, @jrperritt, and/or other gophers checked out what's stubbed out here to see if it makes a consistent library interface (would you want to rely on this).

I'd like to bring in this code to `gophercloud` for `rack`, but:

* the service currently relies on password instead of API key (this is by design, used by the frontend)
* eventually we'll be switching over to OpenStack Magnum

/cc @thomasem

**Comment by jamiehannaford** [comment]
@rgbkrk I'm pretty sure gophercloud [already supports](https://github.com/rackspace/gophercloud/blob/master/auth_options.go#L28) password-based auth for the Rackspace provider. I got it working with:

```go
package main

import (
	"fmt"

	"github.com/rackspace/gophercloud"
	"github.com/rackspace/gophercloud/pagination"
	"github.com/rackspace/gophercloud/rackspace"
	"github.com/rackspace/gophercloud/rackspace/compute/v2/servers"
)

func main() {
	authOpts := gophercloud.AuthOptions{
		Username: "foo",
		Password: "bar",
	}

	client, err := rackspace.AuthenticatedClient(authOpts)
	if err != nil {
		panic(err)
	}

	compute, err := rackspace.NewComputeV2(client, gophercloud.EndpointOpts{
		Region: "IAD",
	})

	err = servers.List(compute, nil).EachPage(func(page pagination.Page) (bool, error) {
		s, _ := servers.ExtractServers(page)
		for _, server := range s {
			fmt.Printf("%s\n", server.ID)
		}

		return true, nil
	})
}
```

Some questions:

1. Is the RCS API documented anywhere?
2. Apart from password-based auth, does it do any wildly different things when compared to other Rackspace APIs?
3. How similar is it to the Magnum API and will it ever be in sync?

**Comment by rgbkrk** [comment]
Oops, I meant to say bring it into gophercloud for the purpose of using it in rack, which relies on API keys.

The RCS API is only documented internally (and not quite what I surfaced here).

It's a good bit different from the magnum API, this is up as stopgap for usability. Once RCS transitions to magnum (in prod) we'll completely switch to that and deprecate these.

**Comment by jamiehannaford** [comment]
Ah okay. Will Rack never support passwords by design, or is that just a current limitation?

**Comment by thomasem** [comment]
The RCS ajax API was meant only for the web UI, really; so it's not considered a versioned, supported contract or anything. It was my understanding that any CLI bindings with that API, if we decide to do that out-of-the-gate, would be considered experimental/beta until we can get Magnum API exposed for an actual contract we intend to use going forward.

I think we can all agree that we don't want to wind up stuck on that API for any substantial length of time in favor of moving to Magnum API. If we get ourselves stuck with it, we wind up not having the flexibility to change the current ajax API how ever we need to in order to support the web UI's needs, and then we wind up being essentially strong-armed into adding features to it for customers and wasting time, ultimately, when we could be working on the thing we actually want to expose. My 2 cents.

**Comment by rgbkrk** [comment]
Alright, API key is no longer an issue. As @thomasem pointed out, we can use Rackspace identity to get an identity token and work with RCS. It's working beautifully now, via GopherCloud.

```go
// NewClusterClientByAPIKey Auth using API Key
func NewClusterClientByAPIKey(endpoint, username, apikey string) (*ClusterClient, error) {
	ao := gophercloud.AuthOptions{
		Username:         username,
		APIKey:           apikey,
		IdentityEndpoint: rackspace.RackspaceUSIdentity,
	}

	return newClusterClient(endpoint, ao)
}
```

**Comment by rgbkrk** [comment]
Fully in action:

```bash
$ rcs
NAME:
  rcs - command line interface to manage swarm clusters
USAGE:
  rcs <command> [clustername] [-username <username>] [-api-key <apiKey>] [-endpoint <endpoint>]

COMMANDS:
  rcs list
  rcs create <clustername>      - create a new cluster
  rcs get <clustername>         - get a cluster by name
  rcs delete <clustername>      - delete a cluster by name
  rcs credentials <clustername> - download credentials to the current directory

FLAGS:
  -username string
    Rackspace username
  -api-key string
    Rackspace API key
  -endpoint string
    RCS API Endpoint (default "https://mycluster.rackspacecloud.com")

ENVIRONMENT VARIABLES:
  RACKSPACE_USERNAME - set instead of -username
  RACKSPACE_APIKEY   - set instead of -api-key
$ rcs list
nbviewer	jupyter	container1-2G	3de6d3b3-dc59-4443-8a3c-dd4741ec168f	4	active
nature		jupyter	container1-4G	3de6d3b3-dc59-4443-8a3c-dd4741ec168f	4	active
moar		jupyter	container1-4G	564ce1eb-3519-4c2d-9ea4-9dc22b55e4de	1	active
$ rcs create another
another	jupyter	container1-4G	564ce1eb-3519-4c2d-9ea4-9dc22b55e4de	1	new
$ rcs credentials moar
key.pem		✅
ca.pem		✅
README.md	✅
ca-key.pem	✅
docker.env	✅
cert.pem	✅
$ source docker.env
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by rgbkrk** [comment]
Closing, as this is now over in [libcarina](https://github.com/rackerlabs/libcarina).
